name: 'publish-image'
description: 'build and publish the image to ECR'
inputs:
  aws-access-key-id: 
    description: 'AWS_ACCESS_KEY_ID'
  aws-secret-access-key: 
    description: 'AWS_SECRET_ACCESS_KEY'
  image: 
    description: 'APP_NAME'
  app-version: 
    description: 'APP_VERSION'
  ecr-path: 
    description: 'ECR_PATH'
runs:
  using: 'node12'
  main: 'lib/index.js'